#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

if [ $language -eq fr ]
then
    ynh_config_add --template="indexfr.html" --destination="$install_dir/index.html"
else
    ynh_config_add --template="indexen.html" --destination="$install_dir/index.html"
fi

chmod 750 "$install_dir/index.html"
chown "$app:www-data" "$install_dir/index.html"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
